#!/bin/sh

if [  $1x == "-q"x  ]; then
    open http://git.qietv.work/QG/qieios/merge_requests/new
elif [  $1x == "-p"x  ]; then
    open http://git.qietv.work/QG/QIEThreePartyLibs/merge_requests/new
else
    echo "-q : 企鹅体育 . -p pod"
fi